export const belowNavbarSuggestions = [
  "new to you",
  "trending",
  "music",
  "live",
  "gaming",
  "news",
  "sports",
  "learning",
  "fashion & beauty",
  "comedy",
  "recently uploaded",
  "watched",

  "360° videos",
  "browse channels",
  "libraries",
  "history",
  "watch later",
  "liked videos",
  "subscriptions",
  "shorts",
  "movies & shows",
  "live now",
  "continue watching",
  "popular on youtube",
  "youtube premium",
];
